"""
CubeMX Configuration Guides - 22 个外设模块的配置向导
=======================================================
从原始单文件 Agent 的 get_cube_mx_guide() 方法提取，
每个模块包含详细的 CubeMX 图形化配置步骤。
"""

CUBE_MX_GUIDES = {
    "gpio": (
        "1. 打开 Pinout & Configuration\n"
        "2. System Core → GPIO → 选择引脚\n"
        "3. 设置:\n"
        "   - GPIO mode: Output Push Pull (LED)\n"
        "   - GPIO Pull-up/Pull-down: No pull-up\n"
        "   - Maximum output speed: Low/Medium/High/Very High\n"
        "4. 生成代码后调用 HAL_GPIO_xxx() 函数\n"
        "提示: 绿色=Output, 黄色=Input, 深绿=Alternate Function"
    ),
    "usart": (
        "1. Connectivity → USART1 → Mode: Asynchronous\n"
        "2. Parameter Settings:\n"
        "   - Baud Rate: 9600 (常用)\n"
        "   - Word Length: 8 Bits\n"
        "   - Parity: None\n"
        "   - Stop Bits: 1\n"
        "3. NVIC Settings → 启用 USART1 global interrupt\n"
        "4. GPIO: TX(PA9) RX(PA10) 自动配置\n"
        "5. 生成代码后在 main.c 的 USER CODE 区域添加回调函数"
    ),
    "spi": (
        "1. Connectivity → SPI1 → Mode: Full-Duplex Master\n"
        "2. Parameter Settings:\n"
        "   - Data Size: 8 Bits\n"
        "   - Clock Polarity (CPOL): Low (Idle时SCK=0)\n"
        "   - Clock Phase (CPHA): 1 Edge (第一个边沿捕获)\n"
        "   - Prescaler (for Baud Rate): 根据从机速度选择 (如 256→~328kHz @84MHz)\n"
        "3. NSS Signal Type: Software (软件片选, 灵活控制多设备)\n"
        "4. GPIO: SCK(PA5), MISO(PA6), MOSI(PA7) + CS引脚(用户自选GPIO)手动配置为Output\n"
        "5. 代码: HAL_SPI_Transmit() / HAL_SPI_Receive() / HAL_SPI_TransmitReceive()"
    ),
    "i2c": (
        "1. Connectivity → I2C1 → I2C → Speed=Fast Mode (400kHz)\n"
        "2. Configuration → Parameters:\n"
        "   - I2C Speed Mode: Fast Mode\n"
        "   - I2C Clock Speed: 400000 (400KHz)\n"
        "3. I2C Timing: CubeMX自动计算或手动选择标准参数\n"
        "4. GPIO: SCL(PB6/PB8), SDA(PB7/PB9) 自动配置\n"
        "   ⚠️ 记得接上拉电阻 (4.7KΩ ~ 10KΩ)\n"
        "5. NVIC: 启用 I2C1 event interrupt / I2C1 error interrupt (可选)\n"
        "6. 常用操作:\n"
        "   - 设备检测: HAL_I2C_IsDeviceReady(&hi2c1, addr, 3, 100)\n"
        "   - 寄存器读写: HAL_I2C_Mem_Read/Write()"
    ),
    "adc": (
        "1. Analog → ADC1 → 勾选 IN0-IN15 (根据使用的引脚)\n"
        "2. Parameter Settings:\n"
        "   - Resolution: 12 bits\n"
        "   - Data Alignment: Right alignment\n"
        "   - Scan Conversion Mode: Disable (单通道) / Enable (多通道)\n"
        "3. Rank 配置: 每个通道分配一个 Rank (优先级)\n"
        "4. Sampling Time: 推荐 55.5 Cycles (平衡精度与速度)\n"
        "5. 如需定时触发: Timers → 选定时器 → Trigger Source Selection → Event Out\n"
        "6. NVIC: 启用 ADC1&EXTI interrupt (中断模式)"
    ),
    "pwm": (
        "1. Timers → 选择定时器 (如 TIM4)\n"
        "2. Channel1 → PWM Generation CH1\n"
        "3. Parameter Settings:\n"
        "   - Prescaler (PSC): 83 (84MHz→1MHz)\n"
        "   - Counter Period (ARR): 999 (1MHz→1kHz PWM频率)\n"
        "   - Pulse (CCR): 500 (50%占空比)\n"
        "4. GPIO 自动配置为 AF (复用功能)\n"
        "5. 代码中调用 HAL_TIM_PWM_Start()\n"
        "6. 运行时用 __HAL_TIM_SET_COMPARE() 调节占空比"
    ),
    "dma": (
        "1. System Core → DMA → Add (添加DMA请求)\n"
        "2. Request 选择外设:\n"
        "   - ADC1: 选择 ADC1\n"
        "   - USART TX/RX: 选择 USARTx_TX / USARTx_RX\n"
        "   - SPI TX/RX: 选择 SPIx_TX / SPIx_RX\n"
        "   - DAC: 选择 DACx_Channel\n"
        "3. Parameter Settings:\n"
        "   - Direction: Peripheral To Memory (接收) / Memory to Peripheral (发送)\n"
        "   - Data Width: Byte/HalfWord/Word (匹配数据类型)\n"
        "   - Mode: Normal (一次传输) / Circular (循环, 用于ADC连续采样)\n"
        "   - Priority: Low/Medium/High/Very High\n"
        "4. 配置好后在代码中调用 HAL_DMA_Start()/HAL_ADC_Start_DMA() 等\n"
        "5. 传输完成回调: HAL_XferCpltCallback() 或 HAL_ADC_ConvHalfCpltCallback(半满)"
    ),
    "rtc": (
        "1. RCC → Low Speed Clock (LSE) → Crystal/Ceramic Resonator (32.768kHz)\n"
        "2. RCC → RTC Clock Sources → Select → LSE\n"
        "3. 勾选 'Activate clock security system' 和 'Activate RTC'\n"
        "4. RTC → Activate Calendar\n"
        "5. Date/Time 初始值 (编译时会写入初始时间)\n"
        "6. Activation → Init/Deinit → Check by default\n"
        "7. NVIC: 启用 RTC global / RTC Alarm interrupt\n"
        "8. ⚠️ 代码中必须先 HAL_RTC_GetTime() 再 HAL_RTC_GetDate()"
    ),
    "oled": (
        "OLED (SSD1306) 使用 I2C 接口, 先配置 I2C1:\n"
        "1. Connectivity → I2C1 → Mode: I2C, Fast Mode (400kHz)\n"
        "2. GPIO: SCL(PB6), SDA(PB7) + 上拉电阻 4.7KΩ\n"
        "3. SSD1306 地址: 0x78 (或 0x7A, 取决于 DCO引脚电平)\n"
        "4. 代码流程:\n"
        "   a. HAL_I2C_IsDeviceReady(&hi2c1, 0x78, 3, 100) 检测设备\n"
        "   b. 发送初始化命令序列 (0xAE关显示, 0x20寻址模式等)\n"
        "   c. 写入显存数据 via HAL_I2C_Mem_Write()\n"
        "   d. 支持中文需要加载字库文件 (GB2312/GBK字库存放在W25Q64 Flash中)"
    ),
    "w25q64": (
        "W25Q64 使用 SPI 接口, 先配置 SPI1:\n"
        "1. Connectivity → SPI1 → Full-Duplex Master\n"
        "2. SPI 参数: CPOL=Low, CPHA=1Edge, Prescaler=256 (低速初始化)/高速可调\n"
        "3. 手动配置一个 GPIO 为 CS 片选引脚 (如 PA4 → Output Push Pull)\n"
        "4. W25Q64 操作要点:\n"
        "   ⚠️ 读操作可直接执行\n"
        "   ⚠️ 写操作前必须: Write Enable (0x06) → 擦除扇区 → 页编程\n"
        "   ⚠️ 每次写入不超过 256 字节 (一页大小)\n"
        "   ⚠️ 擦除以扇区为单位 (4KB), 需等待 BUSY 清零 (~50ms)\n"
        "5. 常用指令:\n"
        "   0x9F=读JEDEC ID | 0x03=读数据 | 0x02=页编程 | 0x20=扇区擦除"
    ),
    "pwr": (
        "1. System Core →_PWR → 勾选所需电源模式:\n"
        "   - Sleep: CPU停止, 外设继续运行 (最低功耗唤醒最快)\n"
        "   - Stop: 大部分时钟停止, SRAM数据保留 (中等功耗)\n"
        "   - Standby: 最低功耗, SRAM丢失, 仅备份域保留 (最低功耗)\n"
        "2. 低功耗模式配置:\n"
        "   Sleep: HAL_SuspendTick(); WFI/WFE 指令进入\n"
        "   Stop: HAL_PWREx_EnterSTOPMode() 或 HAL_PWR_EnterSTOPMode()\n"
        "   Standby: HAL_PWR_EnterSTANDBYMode()\n"
        "3. 唤醒源配置:\n"
        "   - RTC Alarm: 任何模式都可唤醒\n"
        "   - 外部中断 (PA0-PA15): Stop模式下可唤醒\n"
        "   - WKUP pin (PA0): 唯一能唤醒 Standby 的引脚\n"
        "4. PWR 电源控制:\n"
        "   - 调压器电压 scaling: 调低可降低功耗但限制主频\n"
        "   - VBAT 引脚: 接备用电池保持RTC和备份寄存器\n"
        "5. 代码示例:\n"
        "   HAL_SuspendTick();\n"
        "   HAL_PWR_EnterSleepMode(); // 进入Sleep\n"
        "   HAL_ResumeTick();         // 唤醒恢复SysTick"
    ),
    "wdg": (
        "独立看门狗 IWDG:\n"
        "1. System Core → IWDG → 勾选 Activate\n"
        "2. Parameter Settings:\n"
        "   - Prescaler: 分频系数 (如 64, LSI 40kHz/64=625Hz)\n"
        "   - Reload Counter: 重装载值 (如 4095, 约6.5秒超时)\n"
        "   → 超时时间 = (Reload+1) * Prescaler / LSI_freq\n"
        "3. 代码中定期喂狗: HAL_IWDG_Refresh(&hiwdg);\n"
        "4. IWDG 使用独立的 LSI 时钟 (~40kHz), 不受系统时钟影响\n\n"
        "窗口看门狗 WWDG:\n"
        "1. System Core → WWDG → 勾选 Activate\n"
        "2. Parameter Settings:\n"
        "   - Counter: 初始计数值 (如 63=0x3F, 即最大值127的一半)\n"
        "   - Window: 窗口值 (如 64, 必须在此值之前喂狗)\n"
        "   - Prescaler: 分频系数 (如 8, PCLK1/8MHz/8=1MHz)\n"
        "3. WWDG 使用 APB1/PCLK1 时钟, 受时钟影响\n"
        "4. 特性: 早期喂狗也会复位! 必须在窗口范围内刷新"
    ),
    "exti": (
        "1. System Core → GPIO → 选择引脚 (如 PA0)\n"
        "2. GPIO mode: External Interrupt Mode with Rising edge (上升沿触发)\n"
        "   或 Falling edge / Rising/Falling (双边沿, 用于按键消抖)\n"
        "3. System Core → NVIC → 找到对应 EXTI IRQ:\n"
        "   - PA0~PB0→EXTI0_IRQn | PA5~PB5→EXTI9_5_IRQn(共享) | PA10~PB10→EXTI15_10_IRQn(共享)\n"
        "4. 勾选 Enable + 设置优先级\n"
        "5. 代码中实现 HAL_GPIO_EXTI_Callback() 或 EXTIx_IRQHandler()\n"
        "提示: 同一Pin号(Pin0/Pin1/...)的不同端口共用一条EXTI线"
    ),
    "tim_basic": (
        "1. Timers → 选择定时器 (基本定时器TIM6/TIM7 / 通用TIM2-5):\n"
        "2. 时基参数:\n"
        "   - Prescaler (PSC): 分频系数 (如 83, 84MHz→1MHz)\n"
        "   - Counter Period (ARR): 自动重载值 (如 999, 1MHz→1ms定时)\n"
        "3. 中断模式: NVIC Settings → 启用 TIMx global interrupt\n"
        "4. PWM 模式: Channel → PWM Generation CHx, 设 Pulse(占空比)\n"
        "5. 输入捕获: Channel → Input Capture direct mode/Rising\n"
        "6. 输出比较: Channel → Output Compare CHx / PWM Generation\n"
        "7. 定时公式: T = (PSC+1)*(ARR+1) / f_clk"
    ),
    "encoder": (
        "1. Timers → 选择带编码器接口的定时器 (TIM2/TIM3/TIM4 推荐)\n"
        "2. Combined Channels → Encoder Mode (Encoder Mode TI1 and TI2 为正交编码)\n"
        "3. Counter Settings:\n"
        "   - Counter Period: 设为最大 (如 65535, 16位计数范围)\n"
        "   - Encoder mode: Encoder Mode TI1 and TI2 (双边沿计数×4精度)\n"
        "4. Parameter Settings:\n"
        "   - Counter Mode: Up (正转计数增加, 反转减少)\n"
        "   - Encoder Polarity: Rise / Both Edge (双边沿×4分辨率)\n"
        "5. GPIO: CH1/CH2 引脚自动配置为 AF (如 PA6/PA7 for TIM3)\n"
        "6. 代码: __HAL_TIM_ENABLE_IT(&htimx, TIM_SOURCE_UPDATE); HAL_TIM_Encoder_Start()"
    ),
    "usb": (
        "1. Connectivity → USB → Device (FS) → 勾选 Activate\n"
        "2. Middleware → USB_DEVICE → Class For FS IP: Communication Device Class (Virtual Port Com)\n"
        "3. Clock Configuration: USB 需要精确 48MHz 时钟 (RCC配置48MHz USB时钟源)\n"
        "4. USB 中断: NVIC → 启用 USB_HP_CAN1_TX_IRQn / USB_LP_CAN1_RX0_IRQn\n"
        "5. GPIO: DM(PA11), DP(PA12) 自动配置\n"
        "6. 生成代码后关键文件:\n"
        "   - usbd_cdc_if.c/h: 用户回调 (接收发送数据在这里修改)\n"
        "   - usb_device.c: 初始化函数 MX_USB_DEVICE_Init()\n"
        "7. PC端安装 STM32 Virtual COM Port 驱动 (ST官网下载)"
    ),
    "can": (
        "1. Connectivity → CAN → Master Mode (或 Loopback 测试用回环)\n"
        "2. Parameter Settings:\n"
        "   - Prescaler (for Time Quantum): 如 8 (42MHz/8=5.25MHz tq)\n"
        "   - Time Quanta in Bit Segment 1: 13 (TS1)\n"
        "   - Time Quanta in Bit Segment 2: 2 (TS2)\n"
        "   - ReSynchronization Jump Width: 1 (SJW)\n"
        "   → 波特率 = 42MHz / 8*(13+2+1) = 350Kbps (调整参数改变波特率)\n"
        "3. CAN Filter: 配置 ID 过滤 (标准ID 11位 / 扩展ID 29位)\n"
        "4. NVIC: 启用 USB_HP/CAN_TX / USB_LP/CAN_RX0 中断\n"
        "5. GPIO: TX(PB12), RX(PB11) 自动配置, 外接 MCP2551 收发器\n"
        "6. 代码: HAL_CAN_Start(), HAL_CAN_AddTxMessage(), HAL_CAN_GetRxMessage()"
    ),
    "sdio": (
        "1. Connectivity → SDIO → 勾选 Activate\n"
        "2. Parameter Settings:\n"
        "   - Clock Divide: SDIOCLK divide bypass (尽量高速) 或 SDIO_CK_DIV0~DIV255\n"
        "   - Data Bus Width: 4-bit (推荐, 比1位快4倍)\n"
        "   - Clock Edge: Rising\n"
        "3. Middleware → FATFS → 勾选 Activate:\n"
        "   - User Defined: SD Card (使用SDIO接口的SD卡)\n"
        "   - Code generation setting: 勾选 Use DMA\n"
        "   - API: 勾选 f_mount/f_open/f_read/f_write/f_close 等\n"
        "4. NVIC: 启用 SDIO global interrupt\n"
        "5. GPIO: CMD(PC12), D0-D3(PC8-PC11), CK(PC12) 自动配置\n"
        "6. 代码: f_mount(&SDFatFS, SDPath, 1); f_open/f_read/f_write/f_close"
    ),
    "dac": (
        "1. Analog → DAC → Channel1 (PA4) / Channel2 (PA5) → 勾选 OUT\n"
        "2. Parameter Settings:\n"
        "   - Output Buffer: Disable (高速/低阻负载) 或 Enable (大电流驱动)\n"
        "   - Trigger: None (软件触发, 用 HAL_DAC_SetValue())\n"
        "   - 或选择 Timer Trigger (定时器+DMA连续波形输出)\n"
        "3. DMA 模式 (连续波形):\n"
        "   - DAC → Settings → 勾选 DMA Out\n"
        "   - System Core → DMA → 添加 DACx Channel\n"
        "   - Mode: Circular (循环) 或 Normal\n"
        "   - Timers → 选一个定时器作为触发源 (如 TIM6 TRGO)\n"
        "4. GPIO: DAC_OUT1(PA4) / DAC_OUT2(PA5) 自动配置为模拟\n"
        "5. 代码: HAL_DAC_Start() / HAL_DAC_SetValue() / HAL_DAC_Start_DMA()"
    ),
    "flash_eeprom": (
        "⚠️ 内部Flash不需要CubeMX外设配置, 直接在代码中操作\n"
        "1. 确定保存地址 (避开用户程序区):\n"
        "   - F103C8T6 Flash: 64KB, 页大小 1KB (0x08000000 ~ 0x0800FFFF)\n"
        "   - 推荐起始页: 最后几页 (如 0x0800F800 = 第62页)\n"
        "2. 代码步骤:\n"
        "   a. HAL_FLASH_Unlock() 解锁Flash\n"
        "   b. HAL_FLASHEx_ErasePage(页地址) 擦除一整页 (必须先擦除再写)\n"
        "   c. HAL_FLASH_Program(FLASH_TYPEPROGRAM_HALFWORD, 地址, 数据) 写入半字 (16bit)\n"
        "   d. HAL_FLASH_Lock() 锁定Flash\n"
        "3. 注意事项:\n"
        "   - 擦除以页为单位 (1KB), 写入以半字为单位 (2字节)\n"
        "   - 擦写次数寿命约 1万次, 不适合频繁写入\n"
        "   - 擦除期间 CPU 会暂停 (约20~30ms/页)"
    ),
    "rng_crc": (
        "RNG (真随机数生成器):\n"
        "1. 不需要CubeMX配置 (F103无RNG硬件, 仅F4/H7等有)\n"
        "   - 对于F103可用 ADC噪声+时间种子 软件伪随机替代\n"
        "CRC (循环冗余校验):\n"
        "1. Computing → CRC → 勾选 Activate\n"
        "2. Polynomial size: 32bits (标准CRC-32)\n"
        "3. 代码: \n"
        "   - uint32_t crc = HAL_CRC_Calculate(&hcrc, (uint32_t*)data, len/4);\n"
        "   - 适用场景: 数据包校验、通信协议完整性验证、固件完整性检查\n"
        "提示: CRC是纯硬件计算, 极快且不占用CPU"
    ),
    "iap": (
        "⚠️ IAP 需要创建两个独立项目 (Bootloader + App)\n"
        "【项目1: Bootloader】 (@ 0x08000000)\n"
        "1. 正常配置 USART/USB/CAN (用于接收新固件)\n"
        "2. 实现协议解析 (Ymodem/Xmodem/自定义)\n"
        "3. 接收完整固件后:\n"
        "   a. HAL_FLASH_Unlock()\n"
        "   b. 循环擦除App所在Flash页\n"
        "   c. HAL_FLASH_Program() 逐半字写入\n"
        "   d. HAL_FLASH_Lock()\n"
        "4. 校验通过后调用 Jump_To_App()\n"
        "【项目2: App】 (@ 0x08002000, 偏移量=Bootloader大小)\n"
        "1. CubeMX → Linker Settings:\n"
        "   - ROM offset: 0x08002000 (或设置VECT_TAB_OFFSET=0x2000)\n"
        "   - RAM offset/SIZE: 默认不变\n"
        "2. main() 最开始添加:\n"
        "   SCB->VTOR = FLASH_BASE | 0x2000; // 重定向中断向量表\n"
        "3. 编译生成的 .bin 文件用于传输\n"
        "【跳转函数核心代码】\n"
        "typedef void (*pFunction)(void);\n"
        "pFunction Jump_To_Application;\n"
        "uint32_t JumpAddress = *(uint32_t*)(APP_ADDR + 4);\n"
        "Jump_To_Application = (pFunction)JumpAddress;\n"
        "HAL_DeInit(); __disable_irq(); SysTick->CTRL = 0;\n"
        "Jump_To_Application(); // 跳转到App执行"
    ),
}


def get_guide(skill_name: str) -> str:
    """获取指定模块的 CubeMX 配置向导"""
    return CUBE_MX_GUIDES.get(
        skill_name,
        f"'{skill_name}' 的 CubeMX 配置指南待补充"
    )


def list_guides() -> list:
    """返回所有可用向导的模块名称"""
    return sorted(CUBE_MX_GUIDES.keys())
